import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Radagast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="text-gray-600 body-font">
        <div className="container px-5 py-12 mx-auto">
          {/* <div className="flex flex-wrap w-full mb-20 flex-col items-center text-center">
      <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">Wear the Vogue</h1>
      <p className="lg:w-1/2 w-full leading-relaxed text-gray-500">Whatever cardigan tote bag tumblr hexagon brooklyn asymmetrical gentrify, subway tile poke farm-to-table.</p>
    </div> */}
          <div className="flex flex-wrap justify-center items-center">
            <Link href={"/Tshirts"}>
              <div className=" bg-[url('https://prod-img.thesouledstore.com/public/theSoul/uploads/catalog/product/1685172205_1259521.jpg?format=webp&w=360&dpr=1.5')] bg-center bg-no-repeat bg-cover xl:w-1/2 md:w-1/2 p-2 m-1 rounded-lg transition ease-out duration-300 hover:scale-95 ">
                <div className="border border-gray-200 p-6 rounded-lg">
                  <div className="w-10 h-10 inline-flex items-center justify-center rounded-full mb-4"></div>
                  <h2 className="text-4xl text-gray-100 font-medium title-font mb-2 ">
                    Tshirts
                  </h2>
                  <p className="leading-relaxed text-base text-gray-100">
                    trendy and versatile T-shirts that effortlessly combine
                    style and comfort
                  </p>
                </div>
              </div>
            </Link>
            <Link href={"/Shorts"}>
              <div className=" bg-[url('https://prod-img.thesouledstore.com/public/theSoul/uploads/catalog/product/1665634993_3036821.jpg?format=webp&w=360&dpr=1.5')] bg-right xl:w-1/3 md:w-1/2 p-2 m-1 rounded-lg transition ease-out duration-300 hover:scale-95">
                <div className="border border-gray-200 p-6 rounded-lg">
                  <div className="w-10 h-10 inline-flex items-center justify-center rounded-full mb-4"></div>
                  <h2 className="text-4xl text-white font-medium title-font mb-2">
                    Shorts
                  </h2>
                  <p className="leading-relaxed text-base text-gray-100">
                    From casual to athletic, find the perfect pair to beat the
                    heat and elevate your wardrobe
                  </p>
                </div>
              </div>
            </Link>
            <Link href={"/Footwear"}>
              
              <div className=" bg-[url('https://prod-img.thesouledstore.com/public/theSoul/uploads/catalog/product/1676570406_8569193.jpg?format=webp&w=360&dpr=1.5')] bg-right xl:w-1/3 md:w-1/2 p-2 m-1 rounded-lg transition ease-out duration-300 hover:scale-95">
                <div className="border border-gray-200 p-6 rounded-lg">
                  <div className="w-10 h-10 inline-flex items-center justify-center rounded-full mb-4"></div>
                  <h2 className="text-4xl text-gray-100 font-medium title-font mb-2 ">
                    Sole City
                  </h2>
                  <p className="leading-relaxed text-base text-gray-100">
                    collection of trendy and high-performance sneakers
                  </p>
                </div>
              </div>
            </Link>
            <Link href={"/hoodies"}>
              <div className="bg-[url('https://prod-img.thesouledstore.com/public/theSoul/uploads/catalog/product/1669136361_4368029.jpg?format=webp&w=360&dpr=1.5')] bg-center bg-cover bg-no-repeat xl:w-1/2 md:w-1/2 p-2 m-1 rounded-lg transition ease-out duration-300 hover:scale-95">
                <div className="border border-gray-200 p-6 rounded-lg">
                  <div className="w-10 h-10 inline-flex items-center justify-center rounded-full  mb-4"></div>
                  <h2 className="text-4xl text-gray-100 font-medium title-font mb-2">
                    Hoodies
                  </h2>
                  <p className="leading-relaxed text-base text-gray-100">
                    classic pullovers to zip-ups, our hoodies that are both
                    stylish and cozy
                  </p>
                </div>
              </div>
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
